server:
  port: 8761

spring:
  application:
    name: discovery-server
  cloud:
    config:
      enabled: false

groq:
  api:
    key: ${GROQ_API_KEY}
    model: "llama-3.1-8b-instant"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost